// packages/signing/src/signer.ts
import * as ed25519 from "@noble/ed25519";
import { sha512 } from "@noble/hashes/sha512";

import type { Ed25519Keypair, Signer } from "./types.js";

// @noble/ed25519 v2 requires a sync hash function to be configured once.
// We use their recommended path: sha512 from @noble/hashes, sync API.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(ed25519 as any).etc ??= {};
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(ed25519 as any).etc.sha512Sync = (...msgs: Uint8Array[]) =>
  sha512(concat(msgs));

function concat(arrs: readonly Uint8Array[]): Uint8Array {
  const len = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(len);
  let o = 0;
  for (const a of arrs) {
    out.set(a, o);
    o += a.length;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Base58 encode/decode — Bulk uses base58 for all pubkey display (Solana convention)
// ---------------------------------------------------------------------------

const B58_ALPHABET =
  "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

export function base58Encode(bytes: Uint8Array): string {
  if (bytes.length === 0) return "";
  const digits: number[] = [0];
  for (let i = 0; i < bytes.length; i++) {
    let carry = bytes[i]!;
    for (let j = 0; j < digits.length; j++) {
      carry += digits[j]! << 8;
      digits[j] = carry % 58;
      carry = (carry / 58) | 0;
    }
    while (carry > 0) {
      digits.push(carry % 58);
      carry = (carry / 58) | 0;
    }
  }
  // Leading zeros become leading '1'
  let out = "";
  let leadingZeros = 0;
  for (
    ;
    leadingZeros < bytes.length && bytes[leadingZeros] === 0;
    leadingZeros++
  ) {
    out += "1";
  }
  if (leadingZeros === bytes.length) return out;
  for (let i = digits.length - 1; i >= 0; i--) out += B58_ALPHABET[digits[i]!];
  return out;
}

export function base58Decode(s: string): Uint8Array {
  if (s.length === 0) return new Uint8Array();
  const bytes: number[] = [0];
  for (let i = 0; i < s.length; i++) {
    const c = s[i]!;
    const value = B58_ALPHABET.indexOf(c);
    if (value === -1) throw new Error(`invalid base58 char: ${c}`);
    let carry = value;
    for (let j = 0; j < bytes.length; j++) {
      carry += bytes[j]! * 58;
      bytes[j] = carry & 0xff;
      carry >>= 8;
    }
    while (carry > 0) {
      bytes.push(carry & 0xff);
      carry >>= 8;
    }
  }
  let leadingOnes = 0;
  for (let i = 0; i < s.length && s[i] === "1"; i++) leadingOnes++;
  if (leadingOnes === s.length) return new Uint8Array(leadingOnes);
  const out = new Uint8Array(leadingOnes + bytes.length);
  out.set(bytes.reverse(), leadingOnes);
  return out;
}

// ---------------------------------------------------------------------------
// Keypair + Signer
// ---------------------------------------------------------------------------

/**
 * Generate a fresh Ed25519 keypair. Used for minting agent-wallet
 * keys server-side — the private key is stored encrypted-at-rest
 * (KMS in production, environment secret for local dev) and never
 * returned to the client.
 *
 * For user wallets, the keypair is generated by the user's wallet
 * (Phantom, Backpack, Solflare, etc.) and KLUB only ever sees the
 * public key.
 */
export function generateKeypair(): Ed25519Keypair {
  const privateKey = ed25519.utils.randomPrivateKey();
  const publicKey = ed25519.getPublicKey(privateKey);
  return { privateKey, publicKey };
}

/**
 * Derive the public key from a private key. Useful when the
 * private key was loaded from encrypted storage and we need to
 * recompute the pubkey.
 */
export function derivePublicKey(privateKey: Uint8Array): Uint8Array {
  if (privateKey.length !== 32) {
    throw new Error("private key must be 32 bytes");
  }
  return ed25519.getPublicKey(privateKey);
}

/**
 * Build a `Signer` backed by an in-memory private key.
 *
 * When bulk-keychain is published, the replacement will look like:
 *
 *     import { KeychainSigner } from 'bulk-keychain';
 *     const signer = new KeychainSigner({ privateKey });
 *
 * The public interface stays identical.
 */
export function createEd25519Signer(keypair: Ed25519Keypair): Signer {
  if (keypair.privateKey.length !== 32) {
    throw new Error("private key must be 32 bytes");
  }
  if (keypair.publicKey.length !== 32) {
    throw new Error("public key must be 32 bytes");
  }
  return {
    publicKey: keypair.publicKey,
    publicKeyBase58: base58Encode(keypair.publicKey),
    async sign(payload: Uint8Array): Promise<Uint8Array> {
      return ed25519.sign(payload, keypair.privateKey);
    },
  };
}

/**
 * Verify an Ed25519 signature. Used by REST handlers that receive
 * signed client requests, and by tests.
 */
export async function verifyEd25519(params: {
  readonly payload: Uint8Array;
  readonly signature: Uint8Array;
  readonly publicKey: Uint8Array;
}): Promise<boolean> {
  if (params.signature.length !== 64) return false;
  if (params.publicKey.length !== 32) return false;
  try {
    return await ed25519.verify(
      params.signature,
      params.payload,
      params.publicKey,
    );
  } catch {
    return false;
  }
}
